data:
  image_dir: res/test
  label_csv_path: res/sample_submission.csv
  tokenizer_path: res/tokenizer.json

model:
  image_size: 384
  patch_size: 16
  max_seq_len: 256

  num_encoder_layers: 12
  num_decoder_layers: 6

  hidden_dim: 768
  num_attn_heads: 12
  expansion_ratio: 4

predict:
  batch_size: 256
  weight_path: MoT-Base-Finetune.pth

environ:
  name: MoT-Base-Finetune
  precision: 16
