data:
  image_dir: res/test
  label_csv_path: res/sample_submission.csv
  tokenizer_path: res/tokenizer.json

model:
  image_size: 224
  patch_size: 16
  max_seq_len: 256

  num_encoder_layers: 12
  num_decoder_layers: 6

  hidden_dim: 768
  num_attn_heads: 12
  expansion_ratio: 4

predict:
  batch_size: 1024
  weight_path: MoT-Base.pth

environ:
  name: MoT-Base
  precision: 16
