from optimization.cross_entropy import LabelSmoothedCrossEntropy
from optimization.lr_scheduling import CosineDecayLR, LinearDecayLR
from optimization.weight_decay import get_do_decay_params, get_no_decay_params
